poster.pdf : *.tex
	pdflatex --interaction nonstopmode poster.tex >/dev/null 2>/dev/null
	make clean
clean :
	rm -f *.aux *.log *.bbl *.bak *.blg *.toc *.out *.glg *.glo *.gls *.ist *~ *.*~* *.backup
