codex.pdf : *.tex
	pdflatex --interaction nonstopmode codex.tex > /dev/null 2> /dev/null
	songidx titleidx.sxd titleidx.sbx > /dev/null 2> /dev/null
	pdflatex --interaction nonstopmode codex.tex > /dev/null 2> /dev/null
	songidx titleidx.sxd titleidx.sbx > /dev/null 2> /dev/null
	pdflatex --interaction nonstopmode codex.tex > /dev/null 2> /dev/null
